[package]
name = "rust_rocket"
version = "0.1.0"
authors = ["noopy <young_ahn@yonsei.ac.kr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.5"